name: Publish package version to pypi

on:
  pull_request:
    types: ["closed"]
  workflow_dispatch:

jobs:
  publish:
    name: python-package-publishing

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check workflow status
        run: echo "Python testing passed successfully, proceeding to package publication"

      - name: Setup python environment
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install publishing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build and Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
