# This workflow installs dependencies and runs the internal test suite upon
# attempted completion of a pull-request, or a push to the master branch
# It also lints the file with flake8

name: Hidden Markov Test Runner

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: hidden-markov-test-runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout/@v7
      
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
     
      - name: Install python 3.10
        run: uv python install 3.10.17

      - name: Install project dependencies
        run: uv sync --dev

      - name: Run test suite
        run: uv run pytest

